/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoAds.GUI;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import projetoAds.conexao.Conectar;
import projetoAds.conexao.ConexaoBD;
import projetoAds.excecao.ConexaoException;

/**
 *
 * @author Grupo Programação Orientada a Objetos
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jLabel21 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        Cadastro = new javax.swing.JTabbedPane();
        Cliente = new javax.swing.JPanel();
        btnAlterarCli = new javax.swing.JButton();
        btnExcluirCli = new javax.swing.JButton();
        btnIncluirCli = new javax.swing.JButton();
        btnPesquisarCli = new javax.swing.JButton();
        lblNomeCli = new javax.swing.JLabel();
        lblCpfCli = new javax.swing.JLabel();
        txtNomeCli = new javax.swing.JTextField();
        txtCpfCli = new javax.swing.JTextField();
        Fabricante = new javax.swing.JPanel();
        btnAlterarFab = new javax.swing.JButton();
        btnExcluirFab = new javax.swing.JButton();
        btnIncluirFab = new javax.swing.JButton();
        btnPesquisarFab = new javax.swing.JButton();
        lblNomeFab = new javax.swing.JLabel();
        lblCnpjFab = new javax.swing.JLabel();
        lblRazaoFab = new javax.swing.JLabel();
        txtCnpjFab = new javax.swing.JTextField();
        txtNomeFab = new javax.swing.JTextField();
        txtRazaoFab = new javax.swing.JTextField();
        Pagamento = new javax.swing.JPanel();
        lblValorPag = new javax.swing.JLabel();
        lblIdPag = new javax.swing.JLabel();
        btnAlterarPag = new javax.swing.JButton();
        btnExcluirPag = new javax.swing.JButton();
        btnIncluirPag = new javax.swing.JButton();
        btnPesquisarPag = new javax.swing.JButton();
        btnFormaPag = new javax.swing.JButton();
        btnPedidoFormaPag = new javax.swing.JButton();
        txtIdPag = new javax.swing.JTextField();
        txtValorPag = new javax.swing.JTextField();
        Vendedor = new javax.swing.JPanel();
        lblNomeVendedor = new javax.swing.JLabel();
        lblIdVendedor = new javax.swing.JLabel();
        btnAlterarVendedor = new javax.swing.JButton();
        btnExcluirVendedor = new javax.swing.JButton();
        btnIncluirVendedor = new javax.swing.JButton();
        btnPesquisarVendedor = new javax.swing.JButton();
        txtIdVendedor = new javax.swing.JTextField();
        txtNomeVendedor = new javax.swing.JTextField();
        FormaPagamento = new javax.swing.JPanel();
        lblIdFormaPag = new javax.swing.JLabel();
        lblDescFormaPag = new javax.swing.JLabel();
        btnAlterarFormaPag = new javax.swing.JButton();
        btnExcluirFormaPa = new javax.swing.JButton();
        btnIncluirFormaPa = new javax.swing.JButton();
        btnPesquisarFormaPa = new javax.swing.JButton();
        txtDescFormaPag = new javax.swing.JTextField();
        txtIdFormaPag = new javax.swing.JTextField();
        Pedido = new javax.swing.JPanel();
        lblNomePedido = new javax.swing.JLabel();
        lblIdPedido = new javax.swing.JLabel();
        lblDataPedido = new javax.swing.JLabel();
        btnAlterarPedido = new javax.swing.JButton();
        btnExcluirPedido = new javax.swing.JButton();
        btnIncluirPedido = new javax.swing.JButton();
        btnPesquisarPedido = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnVendedor = new javax.swing.JButton();
        txtIdPedido = new javax.swing.JTextField();
        txtNomePedido = new javax.swing.JTextField();
        txtDataPedido = new javax.swing.JTextField();
        Venda = new javax.swing.JPanel();
        lblPrecoVenda = new javax.swing.JLabel();
        lblQtdVenda = new javax.swing.JLabel();
        btnAlterarVenda = new javax.swing.JButton();
        btnExcluirVenda = new javax.swing.JButton();
        btnIncluirVenda = new javax.swing.JButton();
        btnPesquisarVenda = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnPedidoVenda = new javax.swing.JButton();
        txtPrecoVenda = new javax.swing.JTextField();
        txtQtdVenda = new javax.swing.JTextField();
        Produto = new javax.swing.JPanel();
        lblDescProduto = new javax.swing.JLabel();
        lblIdProduto = new javax.swing.JLabel();
        lblEstMinProduto = new javax.swing.JLabel();
        lblEstAtualProduto = new javax.swing.JLabel();
        btnAlterarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        btnIncluirProduto = new javax.swing.JButton();
        btnPesquisarProduto = new javax.swing.JButton();
        btnFabricanteProduto = new javax.swing.JButton();
        txtIdProduto = new javax.swing.JTextField();
        txtDescProduto = new javax.swing.JTextField();
        txtEstMinProduto = new javax.swing.JTextField();
        txtEstAtualProduto = new javax.swing.JTextField();

        jLabel21.setText("jLabel21");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane5.setMaximumSize(new java.awt.Dimension(20767, 30767));
        jTabbedPane5.setPreferredSize(new java.awt.Dimension(778, 346));

        Cadastro.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cadastro.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Cadastro.setFocusable(false);
        Cadastro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cadastro.setPreferredSize(new java.awt.Dimension(867, 309));

        btnAlterarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarCli.setText("Alterar");
        btnAlterarCli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterarCli.setMaximumSize(new java.awt.Dimension(43, 23));
        btnAlterarCli.setMinimumSize(new java.awt.Dimension(43, 23));
        btnAlterarCli.setPreferredSize(new java.awt.Dimension(43, 23));
        btnAlterarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCliActionPerformed(evt);
            }
        });

        btnExcluirCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirCli.setText("Excluir");
        btnExcluirCli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluirCli.setMaximumSize(new java.awt.Dimension(43, 23));
        btnExcluirCli.setMinimumSize(new java.awt.Dimension(43, 23));
        btnExcluirCli.setPreferredSize(new java.awt.Dimension(43, 23));

        btnIncluirCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirCli.setText("Incluir");
        btnIncluirCli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPesquisarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarCli.setText("Pesquisar");
        btnPesquisarCli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNomeCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomeCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeCli.setText("NOME");
        lblNomeCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNomeCli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCpfCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCpfCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpfCli.setText("CPF");
        lblCpfCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNomeCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeCliFocusGained(evt);
            }
        });

        txtCpfCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCpfCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClienteLayout = new javax.swing.GroupLayout(Cliente);
        Cliente.setLayout(ClienteLayout);
        ClienteLayout.setHorizontalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlterarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncluirCli, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirCli, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        ClienteLayout.setVerticalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIncluirCli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirCli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCpfCli)
                                .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeCli)
                            .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Cadastro.addTab("Cliente", Cliente);

        Fabricante.setMaximumSize(new java.awt.Dimension(32667, 32667));

        btnAlterarFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarFab.setText("Alterar");
        btnAlterarFab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterarFab.setMaximumSize(new java.awt.Dimension(43, 23));
        btnAlterarFab.setMinimumSize(new java.awt.Dimension(43, 23));
        btnAlterarFab.setPreferredSize(new java.awt.Dimension(43, 23));
        btnAlterarFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFabActionPerformed(evt);
            }
        });

        btnExcluirFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirFab.setText("Excluir");
        btnExcluirFab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluirFab.setMaximumSize(new java.awt.Dimension(43, 23));
        btnExcluirFab.setMinimumSize(new java.awt.Dimension(43, 23));
        btnExcluirFab.setPreferredSize(new java.awt.Dimension(43, 23));

        btnIncluirFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirFab.setText("Incluir");
        btnIncluirFab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIncluirFab.setMaximumSize(new java.awt.Dimension(43, 23));
        btnIncluirFab.setMinimumSize(new java.awt.Dimension(43, 23));

        btnPesquisarFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarFab.setText("Pesquisar");
        btnPesquisarFab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarFab.setMaximumSize(new java.awt.Dimension(63, 23));
        btnPesquisarFab.setMinimumSize(new java.awt.Dimension(63, 23));
        btnPesquisarFab.setPreferredSize(new java.awt.Dimension(63, 23));

        lblNomeFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomeFab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeFab.setText("NOME");
        lblNomeFab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCnpjFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCnpjFab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCnpjFab.setText("CNPJ");
        lblCnpjFab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCnpjFab.setMaximumSize(new java.awt.Dimension(26, 19));

        lblRazaoFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRazaoFab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRazaoFab.setText("RAZÃO SOCIAL");
        lblRazaoFab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtCnpjFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNomeFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtRazaoFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout FabricanteLayout = new javax.swing.GroupLayout(Fabricante);
        Fabricante.setLayout(FabricanteLayout);
        FabricanteLayout.setHorizontalGroup(
            FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FabricanteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FabricanteLayout.createSequentialGroup()
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNomeFab, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(lblCnpjFab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeFab, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCnpjFab, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FabricanteLayout.createSequentialGroup()
                        .addComponent(lblRazaoFab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRazaoFab)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarFab, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncluirFab, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPesquisarFab, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirFab, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        FabricanteLayout.setVerticalGroup(
            FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FabricanteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FabricanteLayout.createSequentialGroup()
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarFab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarFab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIncluirFab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirFab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FabricanteLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeFab)
                            .addComponent(txtNomeFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCnpjFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCnpjFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRazaoFab)
                            .addComponent(txtRazaoFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Cadastro.addTab("Fabricante", Fabricante);

        lblValorPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValorPag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorPag.setText("VALOR");
        lblValorPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIdPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdPag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdPag.setText("IDENTIFICAÇÃO");
        lblIdPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAlterarPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarPag.setText("Alterar");
        btnAlterarPag.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterarPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPagActionPerformed(evt);
            }
        });

        btnExcluirPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirPag.setText("Excluir");
        btnExcluirPag.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnIncluirPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirPag.setText("Incluir");
        btnIncluirPag.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPesquisarPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarPag.setText("Pesquisar");
        btnPesquisarPag.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFormaPag.setText("Forma de Pagamento");
        btnFormaPag.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPedidoFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPedidoFormaPag.setText("Pedido");
        btnPedidoFormaPag.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIdPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdPag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdPagFocusGained(evt);
            }
        });

        txtValorPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValorPag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorPagFocusGained(evt);
            }
        });

        javax.swing.GroupLayout PagamentoLayout = new javax.swing.GroupLayout(Pagamento);
        Pagamento.setLayout(PagamentoLayout);
        PagamentoLayout.setHorizontalGroup(
            PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagamentoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PagamentoLayout.createSequentialGroup()
                        .addComponent(lblValorPag, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorPag, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PagamentoLayout.createSequentialGroup()
                        .addComponent(lblIdPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdPag, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PagamentoLayout.createSequentialGroup()
                        .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAlterarPag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIncluirPag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluirPag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarPag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPedidoFormaPag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        PagamentoLayout.setVerticalGroup(
            PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagamentoLayout.createSequentialGroup()
                .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PagamentoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarPag, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarPag, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIncluirPag, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirPag, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPedidoFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PagamentoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorPag)
                            .addComponent(txtValorPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdPag)
                            .addComponent(txtIdPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Cadastro.addTab("Pagamento", Pagamento);

        lblNomeVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomeVendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeVendedor.setText("NOME");
        lblNomeVendedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIdVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdVendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdVendedor.setText("IDENTIFICAÇÃO");
        lblIdVendedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAlterarVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarVendedor.setText("Alterar");
        btnAlterarVendedor.setActionCommand("");
        btnAlterarVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarVendedorActionPerformed(evt);
            }
        });

        btnExcluirVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirVendedor.setText("Excluir");
        btnExcluirVendedor.setActionCommand("");
        btnExcluirVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnIncluirVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirVendedor.setText("Incluir");
        btnIncluirVendedor.setActionCommand("");
        btnIncluirVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPesquisarVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarVendedor.setText("Pesquisar");
        btnPesquisarVendedor.setActionCommand("");
        btnPesquisarVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIdVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNomeVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout VendedorLayout = new javax.swing.GroupLayout(Vendedor);
        Vendedor.setLayout(VendedorLayout);
        VendedorLayout.setHorizontalGroup(
            VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendedorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendedorLayout.createSequentialGroup()
                        .addComponent(lblIdVendedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VendedorLayout.createSequentialGroup()
                        .addComponent(lblNomeVendedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncluirVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        VendedorLayout.setVerticalGroup(
            VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendedorLayout.createSequentialGroup()
                .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendedorLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeVendedor)
                            .addComponent(txtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdVendedor)
                            .addComponent(txtIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(VendedorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIncluirVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(76, 76, 76))
        );

        Cadastro.addTab("Vendedor", Vendedor);

        lblIdFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdFormaPag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdFormaPag.setText("IDENTIFICAÇÃO");
        lblIdFormaPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDescFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescFormaPag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescFormaPag.setText("DESCRIÇÃO");
        lblDescFormaPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAlterarFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarFormaPag.setText("Alterar");
        btnAlterarFormaPag.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterarFormaPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFormaPagActionPerformed(evt);
            }
        });

        btnExcluirFormaPa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirFormaPa.setText("Excluir");
        btnExcluirFormaPa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnIncluirFormaPa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirFormaPa.setText("Incluir");
        btnIncluirFormaPa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPesquisarFormaPa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarFormaPa.setText("Pesquisar");
        btnPesquisarFormaPa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDescFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescFormaPag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescFormaPagFocusGained(evt);
            }
        });

        txtIdFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdFormaPag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFormaPagFocusGained(evt);
            }
        });

        javax.swing.GroupLayout FormaPagamentoLayout = new javax.swing.GroupLayout(FormaPagamento);
        FormaPagamento.setLayout(FormaPagamentoLayout);
        FormaPagamentoLayout.setHorizontalGroup(
            FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormaPagamentoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormaPagamentoLayout.createSequentialGroup()
                        .addComponent(lblIdFormaPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormaPagamentoLayout.createSequentialGroup()
                        .addComponent(lblDescFormaPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIncluirFormaPa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisarFormaPa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirFormaPa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
        );
        FormaPagamentoLayout.setVerticalGroup(
            FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormaPagamentoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarFormaPa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdFormaPag))
                .addGap(18, 18, 18)
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirFormaPa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirFormaPa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescFormaPag)
                    .addComponent(txtDescFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Cadastro.addTab("Forma de Pagamento", FormaPagamento);

        lblNomePedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomePedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomePedido.setText("NOME");
        lblNomePedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIdPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdPedido.setText("IDENTIFICAÇÃO");
        lblIdPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDataPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDataPedido.setText("DATA");
        lblDataPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAlterarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarPedido.setText("Alterar");
        btnAlterarPedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPedidoActionPerformed(evt);
            }
        });

        btnExcluirPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirPedido.setText("Excluir");
        btnExcluirPedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnIncluirPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirPedido.setText("Incluir");
        btnIncluirPedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPesquisarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarPedido.setText("Pesquisar");
        btnPesquisarPedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVendedor.setText("Vendedor");
        btnVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedorActionPerformed(evt);
            }
        });

        txtIdPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNomePedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDataPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout PedidoLayout = new javax.swing.GroupLayout(Pedido);
        Pedido.setLayout(PedidoLayout);
        PedidoLayout.setHorizontalGroup(
            PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addComponent(lblDataPedido)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidoLayout.createSequentialGroup()
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PedidoLayout.createSequentialGroup()
                                .addComponent(lblNomePedido)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomePedido))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PedidoLayout.createSequentialGroup()
                                .addComponent(lblIdPedido)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                        .addGap(26, 26, 26))
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addComponent(btnVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)))
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIncluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnExcluirPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        PedidoLayout.setVerticalGroup(
            PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIncluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomePedido)
                            .addComponent(txtNomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdPedido)
                            .addComponent(txtIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataPedido)
                            .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cadastro.addTab("Pedido", Pedido);

        lblPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrecoVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecoVenda.setText("PREÇO");
        lblPrecoVenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblQtdVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQtdVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdVenda.setText("QUANTIDADE DO PRODUTO");
        lblQtdVenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAlterarVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarVenda.setText("Alterar");
        btnAlterarVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarVendaActionPerformed(evt);
            }
        });

        btnExcluirVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirVenda.setText("Excluir");
        btnExcluirVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnIncluirVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirVenda.setText("Incluir");
        btnIncluirVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPesquisarVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarVenda.setText("Pesquisar");
        btnPesquisarVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProduto.setText("Produto");
        btnProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPedidoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPedidoVenda.setText("Pedido");
        btnPedidoVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtQtdVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout VendaLayout = new javax.swing.GroupLayout(Venda);
        Venda.setLayout(VendaLayout);
        VendaLayout.setHorizontalGroup(
            VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(VendaLayout.createSequentialGroup()
                            .addComponent(lblPrecoVenda)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(VendaLayout.createSequentialGroup()
                            .addComponent(lblQtdVenda)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtQtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(VendaLayout.createSequentialGroup()
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlterarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIncluirVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPesquisarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPedidoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        VendaLayout.setVerticalGroup(
            VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendaLayout.createSequentialGroup()
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIncluirVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VendaLayout.createSequentialGroup()
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecoVenda)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQtdVenda)
                            .addComponent(txtQtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedidoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cadastro.addTab("Venda", Venda);

        lblDescProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescProduto.setText("DESCRIÇÃO");
        lblDescProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIdProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdProduto.setText("IDENTIFICAÇÃO");
        lblIdProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEstMinProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstMinProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstMinProduto.setText("ESTOQUE MÍNIMO");
        lblEstMinProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEstAtualProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstAtualProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstAtualProduto.setText("ESTOQUE ATUAL");
        lblEstAtualProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAlterarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarProduto.setText("Alterar");
        btnAlterarProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        btnExcluirProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirProduto.setText("Excluir");
        btnExcluirProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        btnIncluirProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirProduto.setText("Incluir");
        btnIncluirProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPesquisarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarProduto.setText("Pesquisar");
        btnPesquisarProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFabricanteProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFabricanteProduto.setText("Fabricante");
        btnFabricanteProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIdProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDescProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescProdutoActionPerformed(evt);
            }
        });

        txtEstMinProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtEstAtualProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout ProdutoLayout = new javax.swing.GroupLayout(Produto);
        Produto.setLayout(ProdutoLayout);
        ProdutoLayout.setHorizontalGroup(
            ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdutoLayout.createSequentialGroup()
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstAtualProduto)
                            .addComponent(lblEstMinProduto))
                        .addGap(18, 18, 18)
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEstAtualProduto)
                            .addComponent(txtEstMinProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProdutoLayout.createSequentialGroup()
                        .addComponent(lblIdProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProdutoLayout.createSequentialGroup()
                        .addComponent(lblDescProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdutoLayout.createSequentialGroup()
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIncluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnFabricanteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        ProdutoLayout.setVerticalGroup(
            ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProdutoLayout.createSequentialGroup()
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIncluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFabricanteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstAtualProduto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProdutoLayout.createSequentialGroup()
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescProduto)
                            .addComponent(txtDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdProduto)
                            .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstMinProduto)
                            .addGroup(ProdutoLayout.createSequentialGroup()
                                .addComponent(txtEstMinProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEstAtualProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        Cadastro.addTab("Produto", Produto);

        jTabbedPane5.addTab("Cadastro", Cadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarCliActionPerformed

    private void btnAlterarFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarFabActionPerformed

    private void btnAlterarPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarPagActionPerformed

    private void btnAlterarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarVendedorActionPerformed

    private void btnAlterarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarPedidoActionPerformed

    private void btnAlterarFormaPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFormaPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarFormaPagActionPerformed

    private void btnAlterarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarVendaActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void txtCpfCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfCliActionPerformed

    private void txtDescProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescProdutoActionPerformed

    private void txtNomeCliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCliFocusGained

    }//GEN-LAST:event_txtNomeCliFocusGained

    private void txtIdFormaPagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFormaPagFocusGained
        if (this.txtIdFormaPag.getText().equals("")) {
            txtIdFormaPag.grabFocus();
        }
    }//GEN-LAST:event_txtIdFormaPagFocusGained

    private void txtDescFormaPagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescFormaPagFocusGained
        if (this.txtDescFormaPag.getText().equals("")) {
            txtDescFormaPag.grabFocus();
        }
    }//GEN-LAST:event_txtDescFormaPagFocusGained

    private void txtValorPagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorPagFocusGained
        if (this.txtValorPag.getText().equals("")) {
            txtValorPag.grabFocus();
        }
    }//GEN-LAST:event_txtValorPagFocusGained

    private void txtIdPagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdPagFocusGained
        if (this.txtIdPag.getText().equals("")) {
            txtIdPag.grabFocus();
        }
    }//GEN-LAST:event_txtIdPagFocusGained

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        ConexaoBD c;
        c = Conectar.getInstancia();

        try {
            c.conectar();
            System.out.println("Massa!");
        } catch (ConexaoException e) {
            System.out.println("Não foi dessa vez!");
        }

        try {
            // Set System L&F
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Cadastro;
    private javax.swing.JPanel Cliente;
    private javax.swing.JPanel Fabricante;
    private javax.swing.JPanel FormaPagamento;
    private javax.swing.JPanel Pagamento;
    private javax.swing.JPanel Pedido;
    private javax.swing.JPanel Produto;
    private javax.swing.JPanel Venda;
    private javax.swing.JPanel Vendedor;
    private javax.swing.JButton btnAlterarCli;
    private javax.swing.JButton btnAlterarFab;
    private javax.swing.JButton btnAlterarFormaPag;
    private javax.swing.JButton btnAlterarPag;
    private javax.swing.JButton btnAlterarPedido;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnAlterarVenda;
    private javax.swing.JButton btnAlterarVendedor;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnExcluirCli;
    private javax.swing.JButton btnExcluirFab;
    private javax.swing.JButton btnExcluirFormaPa;
    private javax.swing.JButton btnExcluirPag;
    private javax.swing.JButton btnExcluirPedido;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnExcluirVenda;
    private javax.swing.JButton btnExcluirVendedor;
    private javax.swing.JButton btnFabricanteProduto;
    private javax.swing.JButton btnFormaPag;
    private javax.swing.JButton btnIncluirCli;
    private javax.swing.JButton btnIncluirFab;
    private javax.swing.JButton btnIncluirFormaPa;
    private javax.swing.JButton btnIncluirPag;
    private javax.swing.JButton btnIncluirPedido;
    private javax.swing.JButton btnIncluirProduto;
    private javax.swing.JButton btnIncluirVenda;
    private javax.swing.JButton btnIncluirVendedor;
    private javax.swing.JButton btnPedidoFormaPag;
    private javax.swing.JButton btnPedidoVenda;
    private javax.swing.JButton btnPesquisarCli;
    private javax.swing.JButton btnPesquisarFab;
    private javax.swing.JButton btnPesquisarFormaPa;
    private javax.swing.JButton btnPesquisarPag;
    private javax.swing.JButton btnPesquisarPedido;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JButton btnPesquisarVenda;
    private javax.swing.JButton btnPesquisarVendedor;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnVendedor;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JLabel lblCnpjFab;
    private javax.swing.JLabel lblCpfCli;
    private javax.swing.JLabel lblDataPedido;
    private javax.swing.JLabel lblDescFormaPag;
    private javax.swing.JLabel lblDescProduto;
    private javax.swing.JLabel lblEstAtualProduto;
    private javax.swing.JLabel lblEstMinProduto;
    private javax.swing.JLabel lblIdFormaPag;
    private javax.swing.JLabel lblIdPag;
    private javax.swing.JLabel lblIdPedido;
    private javax.swing.JLabel lblIdProduto;
    private javax.swing.JLabel lblIdVendedor;
    private javax.swing.JLabel lblNomeCli;
    private javax.swing.JLabel lblNomeFab;
    private javax.swing.JLabel lblNomePedido;
    private javax.swing.JLabel lblNomeVendedor;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JLabel lblQtdVenda;
    private javax.swing.JLabel lblRazaoFab;
    private javax.swing.JLabel lblValorPag;
    private javax.swing.JTextField txtCnpjFab;
    private javax.swing.JTextField txtCpfCli;
    private javax.swing.JTextField txtDataPedido;
    private javax.swing.JTextField txtDescFormaPag;
    private javax.swing.JTextField txtDescProduto;
    private javax.swing.JTextField txtEstAtualProduto;
    private javax.swing.JTextField txtEstMinProduto;
    private javax.swing.JTextField txtIdFormaPag;
    private javax.swing.JTextField txtIdPag;
    private javax.swing.JTextField txtIdPedido;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtIdVendedor;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JTextField txtNomeFab;
    private javax.swing.JTextField txtNomePedido;
    private javax.swing.JTextField txtNomeVendedor;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtQtdVenda;
    private javax.swing.JTextField txtRazaoFab;
    private javax.swing.JTextField txtValorPag;
    // End of variables declaration//GEN-END:variables
}
