/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoAds.GUI;

/**
 *
 * @author Annie
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jLabel21 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Cliente = new javax.swing.JPanel();
        btnAlterarCli = new javax.swing.JButton();
        btnExcluirCli = new javax.swing.JButton();
        btnIncluirCli = new javax.swing.JButton();
        btnPesquisarCli = new javax.swing.JButton();
        lblNomeCli = new javax.swing.JLabel();
        lblCpfCli = new javax.swing.JLabel();
        txtNomeCli = new javax.swing.JTextField();
        txtCpfCli = new javax.swing.JTextField();
        Fabricante = new javax.swing.JPanel();
        btnAlterarFab = new javax.swing.JButton();
        btnExcluirFab = new javax.swing.JButton();
        btnIncluirFab = new javax.swing.JButton();
        btnPesquisarFab = new javax.swing.JButton();
        lblNomeFab = new javax.swing.JLabel();
        lblCnpjFab = new javax.swing.JLabel();
        lblRazaoFab = new javax.swing.JLabel();
        txtCnpjFab = new javax.swing.JTextField();
        txtNomeFab = new javax.swing.JTextField();
        txtRazaoFab = new javax.swing.JTextField();
        Pagamento = new javax.swing.JPanel();
        lblValorPag = new javax.swing.JLabel();
        lblIdPag = new javax.swing.JLabel();
        btnAlterarPag = new javax.swing.JButton();
        btnExcluirPag = new javax.swing.JButton();
        btnIncluirPag = new javax.swing.JButton();
        btnPesquisarPag = new javax.swing.JButton();
        btnFormaPag = new javax.swing.JButton();
        btnPedidoFormaPag = new javax.swing.JButton();
        txtIdPag = new javax.swing.JTextField();
        txtValorPag = new javax.swing.JTextField();
        Vendedor = new javax.swing.JPanel();
        lblNomeVendedor = new javax.swing.JLabel();
        lblIdVendedor = new javax.swing.JLabel();
        btnAlterarVendedor = new javax.swing.JButton();
        btnExcluirVendedor = new javax.swing.JButton();
        btnIncluirVendedor = new javax.swing.JButton();
        btnPesquisarVendedor = new javax.swing.JButton();
        txtIdVendedor = new javax.swing.JTextField();
        txtNomeVendedor = new javax.swing.JTextField();
        FormaPagamento = new javax.swing.JPanel();
        lblIdFormaPag = new javax.swing.JLabel();
        lblDescFormaPag = new javax.swing.JLabel();
        btnAlterarFormaPag = new javax.swing.JButton();
        btnExcluirFormaPa = new javax.swing.JButton();
        btnIncluirFormaPa = new javax.swing.JButton();
        btnPesquisarFormaPa = new javax.swing.JButton();
        txtDescFormaPag = new javax.swing.JTextField();
        txtIdFormaPag = new javax.swing.JTextField();
        Pedido = new javax.swing.JPanel();
        lblNomePedido = new javax.swing.JLabel();
        lblIdPedido = new javax.swing.JLabel();
        lblDataPedido = new javax.swing.JLabel();
        btnAlterarPedido = new javax.swing.JButton();
        btnExcluirPedido = new javax.swing.JButton();
        btnIncluirPedido = new javax.swing.JButton();
        btnPesquisarPedido = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnVendedor = new javax.swing.JButton();
        txtIdPedido = new javax.swing.JTextField();
        txtNomePedido = new javax.swing.JTextField();
        txtDataPedido = new javax.swing.JTextField();
        Venda = new javax.swing.JPanel();
        lblPrecoVenda = new javax.swing.JLabel();
        lblQtdVenda = new javax.swing.JLabel();
        btnAlterarVenda = new javax.swing.JButton();
        btnExcluirVenda = new javax.swing.JButton();
        btnIncluirVenda = new javax.swing.JButton();
        btnPesquisarVenda = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnPedidoVenda = new javax.swing.JButton();
        txtPrecoVenda = new javax.swing.JTextField();
        txtQtdVenda = new javax.swing.JTextField();
        Produto = new javax.swing.JPanel();
        lblDescProduto = new javax.swing.JLabel();
        lblIdProduto = new javax.swing.JLabel();
        lblEstMinProduto = new javax.swing.JLabel();
        lblEstAtualProduto = new javax.swing.JLabel();
        btnAlterarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        btnIncluirProduto = new javax.swing.JButton();
        btnPesquisarProduto = new javax.swing.JButton();
        btnFabricanteProduto = new javax.swing.JButton();
        txtIdProduto = new javax.swing.JTextField();
        txtDescProduto = new javax.swing.JTextField();
        txtEstMinProduto = new javax.swing.JTextField();
        txtEstAtualProduto = new javax.swing.JTextField();

        jLabel21.setText("jLabel21");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(2047483647, 2047483647));
        setPreferredSize(new java.awt.Dimension(667, 209));

        jTabbedPane5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane5.setMaximumSize(new java.awt.Dimension(22767, 32767));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAlterarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarCli.setText("Alterar");
        btnAlterarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCliActionPerformed(evt);
            }
        });

        btnExcluirCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirCli.setText("Excluir");

        btnIncluirCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirCli.setText("Incluir");

        btnPesquisarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarCli.setText("Pesquisar");

        lblNomeCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomeCli.setText("NOME");

        lblCpfCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCpfCli.setText("CPF");

        txtNomeCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeCliFocusGained(evt);
            }
        });

        txtCpfCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCpfCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClienteLayout = new javax.swing.GroupLayout(Cliente);
        Cliente.setLayout(ClienteLayout);
        ClienteLayout.setHorizontalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeCli)
                    .addComponent(lblCpfCli))
                .addGap(28, 28, 28)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlterarCli)
                    .addComponent(btnIncluirCli))
                .addGap(43, 43, 43)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisarCli)
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnExcluirCli)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        ClienteLayout.setVerticalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClienteLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCli)
                    .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarCli)
                    .addComponent(btnPesquisarCli))
                .addGap(18, 18, 18)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCli)
                    .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncluirCli)
                    .addComponent(btnExcluirCli))
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Cliente", Cliente);

        btnAlterarFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarFab.setText("Alterar");
        btnAlterarFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFabActionPerformed(evt);
            }
        });

        btnExcluirFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirFab.setText("Excluir");

        btnIncluirFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirFab.setText("Incluir");

        btnPesquisarFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarFab.setText("Pesquisar");

        lblNomeFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomeFab.setText("NOME");

        lblCnpjFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCnpjFab.setText("CNPJ");

        lblRazaoFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRazaoFab.setText("RAZÃO SOCIAL");

        txtCnpjFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNomeFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtRazaoFab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout FabricanteLayout = new javax.swing.GroupLayout(Fabricante);
        Fabricante.setLayout(FabricanteLayout);
        FabricanteLayout.setHorizontalGroup(
            FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FabricanteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeFab)
                    .addComponent(lblCnpjFab)
                    .addComponent(lblRazaoFab))
                .addGap(40, 40, 40)
                .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FabricanteLayout.createSequentialGroup()
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCnpjFab, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeFab, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIncluirFab)
                            .addComponent(btnAlterarFab))
                        .addGap(27, 27, 27)
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPesquisarFab)
                            .addGroup(FabricanteLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnExcluirFab))))
                    .addComponent(txtRazaoFab, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        FabricanteLayout.setVerticalGroup(
            FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FabricanteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FabricanteLayout.createSequentialGroup()
                        .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FabricanteLayout.createSequentialGroup()
                                .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAlterarFab)
                                    .addComponent(btnPesquisarFab))
                                .addGap(18, 18, 18)
                                .addGroup(FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnIncluirFab)
                                    .addComponent(btnExcluirFab)))
                            .addGroup(FabricanteLayout.createSequentialGroup()
                                .addComponent(txtNomeFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCnpjFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addComponent(txtRazaoFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FabricanteLayout.createSequentialGroup()
                        .addComponent(lblNomeFab)
                        .addGap(15, 15, 15)
                        .addComponent(lblCnpjFab)
                        .addGap(11, 11, 11)
                        .addComponent(lblRazaoFab)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fabricante", Fabricante);

        lblValorPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValorPag.setText("VALOR");

        lblIdPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdPag.setText("IDENTIFICAÇÃO");

        btnAlterarPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarPag.setText("Alterar");
        btnAlterarPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPagActionPerformed(evt);
            }
        });

        btnExcluirPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirPag.setText("Excluir");

        btnIncluirPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirPag.setText("Incluir");

        btnPesquisarPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarPag.setText("Pesquisar");

        btnFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFormaPag.setText("Forma de Pagamento");

        btnPedidoFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPedidoFormaPag.setText("Forma de Pagamento");

        txtIdPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdPag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdPagFocusGained(evt);
            }
        });

        txtValorPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValorPag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorPagFocusGained(evt);
            }
        });

        javax.swing.GroupLayout PagamentoLayout = new javax.swing.GroupLayout(Pagamento);
        Pagamento.setLayout(PagamentoLayout);
        PagamentoLayout.setHorizontalGroup(
            PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagamentoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPedidoFormaPag)
                    .addGroup(PagamentoLayout.createSequentialGroup()
                        .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PagamentoLayout.createSequentialGroup()
                                .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdPag)
                                    .addComponent(lblValorPag))
                                .addGap(18, 18, 18)
                                .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtValorPag)
                                    .addComponent(txtIdPag, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAlterarPag)
                                    .addComponent(btnIncluirPag)))
                            .addGroup(PagamentoLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btnFormaPag)))
                        .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PagamentoLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnPesquisarPag))
                            .addGroup(PagamentoLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnExcluirPag)))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        PagamentoLayout.setVerticalGroup(
            PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagamentoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PagamentoLayout.createSequentialGroup()
                        .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarPag)
                            .addComponent(btnPesquisarPag))
                        .addGap(18, 18, 18)
                        .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnIncluirPag)
                                .addComponent(btnExcluirPag))))
                    .addGroup(PagamentoLayout.createSequentialGroup()
                        .addComponent(lblValorPag)
                        .addGap(9, 9, 9)
                        .addComponent(lblIdPag)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormaPag)
                    .addComponent(btnPedidoFormaPag))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagamento", Pagamento);

        lblNomeVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomeVendedor.setText("NOME");

        lblIdVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdVendedor.setText("IDENTIFICAÇÃO");

        btnAlterarVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarVendedor.setText("Alterar");
        btnAlterarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarVendedorActionPerformed(evt);
            }
        });

        btnExcluirVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirVendedor.setText("Excluir");

        btnIncluirVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirVendedor.setText("Incluir");

        btnPesquisarVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarVendedor.setText("Pesquisar");

        txtIdVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNomeVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout VendedorLayout = new javax.swing.GroupLayout(Vendedor);
        Vendedor.setLayout(VendedorLayout);
        VendedorLayout.setHorizontalGroup(
            VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendedorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdVendedor)
                    .addComponent(lblNomeVendedor))
                .addGap(36, 36, 36)
                .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarVendedor)
                    .addComponent(btnIncluirVendedor))
                .addGap(33, 33, 33)
                .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisarVendedor)
                    .addGroup(VendedorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnExcluirVendedor)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        VendedorLayout.setVerticalGroup(
            VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendedorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendedorLayout.createSequentialGroup()
                        .addComponent(txtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VendedorLayout.createSequentialGroup()
                        .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeVendedor)
                            .addComponent(btnAlterarVendedor)
                            .addComponent(btnPesquisarVendedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdVendedor)
                            .addGroup(VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnIncluirVendedor)
                                .addComponent(btnExcluirVendedor)))))
                .addGap(84, 84, 84))
        );

        jTabbedPane1.addTab("Vendedor", Vendedor);

        lblIdFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdFormaPag.setText("IDENTIFICAÇÃO");

        lblDescFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescFormaPag.setText("DESCRIÇÃO");

        btnAlterarFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarFormaPag.setText("Alterar");
        btnAlterarFormaPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFormaPagActionPerformed(evt);
            }
        });

        btnExcluirFormaPa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirFormaPa.setText("Excluir");

        btnIncluirFormaPa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirFormaPa.setText("Incluir");

        btnPesquisarFormaPa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarFormaPa.setText("Pesquisar");

        txtDescFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescFormaPag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescFormaPagFocusGained(evt);
            }
        });

        txtIdFormaPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdFormaPag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFormaPagFocusGained(evt);
            }
        });

        javax.swing.GroupLayout FormaPagamentoLayout = new javax.swing.GroupLayout(FormaPagamento);
        FormaPagamento.setLayout(FormaPagamentoLayout);
        FormaPagamentoLayout.setHorizontalGroup(
            FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormaPagamentoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescFormaPag)
                    .addComponent(lblIdFormaPag))
                .addGap(18, 18, 18)
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIncluirFormaPa)
                    .addComponent(btnAlterarFormaPag))
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormaPagamentoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnPesquisarFormaPa)
                        .addGap(108, 108, 108))
                    .addGroup(FormaPagamentoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnExcluirFormaPa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        FormaPagamentoLayout.setVerticalGroup(
            FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormaPagamentoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdFormaPag)
                    .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlterarFormaPag)
                        .addComponent(btnPesquisarFormaPa)))
                .addGap(18, 18, 18)
                .addGroup(FormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescFormaPag)
                    .addComponent(btnIncluirFormaPa)
                    .addComponent(btnExcluirFormaPa))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Forma de Pagamento", FormaPagamento);

        lblNomePedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomePedido.setText("NOME");

        lblIdPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdPedido.setText("IDENTIFICAÇÃO");

        lblDataPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataPedido.setText("DATA");

        btnAlterarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarPedido.setText("Alterar");
        btnAlterarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPedidoActionPerformed(evt);
            }
        });

        btnExcluirPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirPedido.setText("Excluir");

        btnIncluirPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirPedido.setText("Incluir");

        btnPesquisarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarPedido.setText("Pesquisar");

        btnCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCliente.setText("Cliente");

        btnVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVendedor.setText("Vendedor");

        txtIdPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNomePedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDataPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout PedidoLayout = new javax.swing.GroupLayout(Pedido);
        Pedido.setLayout(PedidoLayout);
        PedidoLayout.setHorizontalGroup(
            PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdPedido)
                            .addComponent(lblNomePedido)
                            .addComponent(lblDataPedido))
                        .addGap(18, 18, 18)
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PedidoLayout.createSequentialGroup()
                                .addComponent(btnIncluirPedido)
                                .addGap(48, 48, 48)
                                .addComponent(btnExcluirPedido)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addGroup(PedidoLayout.createSequentialGroup()
                                .addComponent(btnAlterarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPesquisarPedido)))
                        .addGap(112, 112, 112))
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnVendedor)
                        .addGap(71, 71, 71)
                        .addComponent(btnCliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PedidoLayout.setVerticalGroup(
            PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoLayout.createSequentialGroup()
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PedidoLayout.createSequentialGroup()
                                .addComponent(lblNomePedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIdPedido))
                            .addGroup(PedidoLayout.createSequentialGroup()
                                .addComponent(txtNomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataPedido))))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarPedido)
                            .addComponent(btnPesquisarPedido))
                        .addGap(30, 30, 30)
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIncluirPedido)
                            .addComponent(btnExcluirPedido))
                        .addGap(18, 18, 18)))
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente)
                    .addComponent(btnVendedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pedido", Pedido);

        lblPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrecoVenda.setText("PREÇO");

        lblQtdVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQtdVenda.setText("QUANTIDADE DO PRODUTO");

        btnAlterarVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarVenda.setText("Alterar");
        btnAlterarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarVendaActionPerformed(evt);
            }
        });

        btnExcluirVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirVenda.setText("Excluir");

        btnIncluirVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirVenda.setText("Incluir");

        btnPesquisarVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarVenda.setText("Pesquisar");

        btnProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProduto.setText("Produto");

        btnPedidoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPedidoVenda.setText("Pedido");

        txtPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtQtdVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout VendaLayout = new javax.swing.GroupLayout(Venda);
        Venda.setLayout(VendaLayout);
        VendaLayout.setHorizontalGroup(
            VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendaLayout.createSequentialGroup()
                .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VendaLayout.createSequentialGroup()
                                .addComponent(lblPrecoVenda)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VendaLayout.createSequentialGroup()
                                .addComponent(lblQtdVenda)
                                .addGap(18, 18, 18)
                                .addComponent(txtQtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VendaLayout.createSequentialGroup()
                                .addComponent(btnIncluirVenda)
                                .addGap(40, 40, 40)
                                .addComponent(btnExcluirVenda))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VendaLayout.createSequentialGroup()
                                .addComponent(btnAlterarVenda)
                                .addGap(30, 30, 30)
                                .addComponent(btnPesquisarVenda))))
                    .addGroup(VendaLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnProduto)
                        .addGap(61, 61, 61)
                        .addComponent(btnPedidoVenda)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        VendaLayout.setVerticalGroup(
            VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendaLayout.createSequentialGroup()
                .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecoVenda)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQtdVenda)
                            .addComponent(txtQtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(VendaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarVenda)
                            .addComponent(btnPesquisarVenda))
                        .addGap(18, 18, 18)
                        .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIncluirVenda)
                            .addComponent(btnExcluirVenda))))
                .addGap(18, 18, 18)
                .addGroup(VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProduto)
                    .addComponent(btnPedidoVenda))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Venda", Venda);

        lblDescProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescProduto.setText("DESCRIÇÃO");

        lblIdProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdProduto.setText("IDENTIFICAÇÃO");

        lblEstMinProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstMinProduto.setText("ESTOQUE MÍNIMO");

        lblEstAtualProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstAtualProduto.setText("ESTOQUE ATUAL");

        btnAlterarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarProduto.setText("Alterar");
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        btnExcluirProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirProduto.setText("Excluir");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        btnIncluirProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluirProduto.setText("Incluir");

        btnPesquisarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarProduto.setText("Pesquisar");

        btnFabricanteProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFabricanteProduto.setText("Fabricante");

        txtIdProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDescProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescProdutoActionPerformed(evt);
            }
        });

        txtEstMinProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtEstAtualProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout ProdutoLayout = new javax.swing.GroupLayout(Produto);
        Produto.setLayout(ProdutoLayout);
        ProdutoLayout.setHorizontalGroup(
            ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdutoLayout.createSequentialGroup()
                        .addComponent(lblDescProduto)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProdutoLayout.createSequentialGroup()
                            .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ProdutoLayout.createSequentialGroup()
                                    .addComponent(lblEstAtualProduto)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProdutoLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(lblEstMinProduto)))
                            .addGap(18, 18, 18)
                            .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEstAtualProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEstMinProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ProdutoLayout.createSequentialGroup()
                            .addComponent(lblIdProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdutoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAlterarProduto)
                            .addComponent(btnIncluirProduto))
                        .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProdutoLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnPesquisarProduto))
                            .addGroup(ProdutoLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnExcluirProduto))))
                    .addGroup(ProdutoLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnFabricanteProduto)))
                .addContainerGap())
        );
        ProdutoLayout.setVerticalGroup(
            ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescProduto)
                    .addComponent(txtDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProduto)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstMinProduto)
                    .addComponent(txtEstMinProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstAtualProduto)
                    .addComponent(txtEstAtualProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(ProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarProduto)
                    .addComponent(btnPesquisarProduto))
                .addGap(18, 18, 18)
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirProduto)
                    .addComponent(btnExcluirProduto))
                .addGap(31, 31, 31)
                .addComponent(btnFabricanteProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produto", Produto);

        jTabbedPane5.addTab("Cadastro", jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarCliActionPerformed

    private void btnAlterarFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarFabActionPerformed

    private void btnAlterarPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarPagActionPerformed

    private void btnAlterarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarVendedorActionPerformed

    private void btnAlterarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarPedidoActionPerformed

    private void btnAlterarFormaPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFormaPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarFormaPagActionPerformed

    private void btnAlterarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarVendaActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void txtCpfCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfCliActionPerformed

    private void txtDescProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescProdutoActionPerformed

    private void txtNomeCliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCliFocusGained

    }//GEN-LAST:event_txtNomeCliFocusGained

    private void txtIdFormaPagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFormaPagFocusGained
        if (this.txtIdFormaPag.getText().equals("")) {
            txtIdFormaPag.grabFocus();
        }
    }//GEN-LAST:event_txtIdFormaPagFocusGained

    private void txtDescFormaPagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescFormaPagFocusGained
        if (this.txtDescFormaPag.getText().equals("")) {
            txtDescFormaPag.grabFocus();
        }
    }//GEN-LAST:event_txtDescFormaPagFocusGained

    private void txtValorPagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorPagFocusGained
        if (this.txtValorPag.getText().equals("")) {
            txtValorPag.grabFocus();
        }
    }//GEN-LAST:event_txtValorPagFocusGained

    private void txtIdPagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdPagFocusGained
        if (this.txtIdPag.getText().equals("")) {
            txtIdPag.grabFocus();
        }
    }//GEN-LAST:event_txtIdPagFocusGained

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cliente;
    private javax.swing.JPanel Fabricante;
    private javax.swing.JPanel FormaPagamento;
    private javax.swing.JPanel Pagamento;
    private javax.swing.JPanel Pedido;
    private javax.swing.JPanel Produto;
    private javax.swing.JPanel Venda;
    private javax.swing.JPanel Vendedor;
    private javax.swing.JButton btnAlterarCli;
    private javax.swing.JButton btnAlterarFab;
    private javax.swing.JButton btnAlterarFormaPag;
    private javax.swing.JButton btnAlterarPag;
    private javax.swing.JButton btnAlterarPedido;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnAlterarVenda;
    private javax.swing.JButton btnAlterarVendedor;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnExcluirCli;
    private javax.swing.JButton btnExcluirFab;
    private javax.swing.JButton btnExcluirFormaPa;
    private javax.swing.JButton btnExcluirPag;
    private javax.swing.JButton btnExcluirPedido;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnExcluirVenda;
    private javax.swing.JButton btnExcluirVendedor;
    private javax.swing.JButton btnFabricanteProduto;
    private javax.swing.JButton btnFormaPag;
    private javax.swing.JButton btnIncluirCli;
    private javax.swing.JButton btnIncluirFab;
    private javax.swing.JButton btnIncluirFormaPa;
    private javax.swing.JButton btnIncluirPag;
    private javax.swing.JButton btnIncluirPedido;
    private javax.swing.JButton btnIncluirProduto;
    private javax.swing.JButton btnIncluirVenda;
    private javax.swing.JButton btnIncluirVendedor;
    private javax.swing.JButton btnPedidoFormaPag;
    private javax.swing.JButton btnPedidoVenda;
    private javax.swing.JButton btnPesquisarCli;
    private javax.swing.JButton btnPesquisarFab;
    private javax.swing.JButton btnPesquisarFormaPa;
    private javax.swing.JButton btnPesquisarPag;
    private javax.swing.JButton btnPesquisarPedido;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JButton btnPesquisarVenda;
    private javax.swing.JButton btnPesquisarVendedor;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnVendedor;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JLabel lblCnpjFab;
    private javax.swing.JLabel lblCpfCli;
    private javax.swing.JLabel lblDataPedido;
    private javax.swing.JLabel lblDescFormaPag;
    private javax.swing.JLabel lblDescProduto;
    private javax.swing.JLabel lblEstAtualProduto;
    private javax.swing.JLabel lblEstMinProduto;
    private javax.swing.JLabel lblIdFormaPag;
    private javax.swing.JLabel lblIdPag;
    private javax.swing.JLabel lblIdPedido;
    private javax.swing.JLabel lblIdProduto;
    private javax.swing.JLabel lblIdVendedor;
    private javax.swing.JLabel lblNomeCli;
    private javax.swing.JLabel lblNomeFab;
    private javax.swing.JLabel lblNomePedido;
    private javax.swing.JLabel lblNomeVendedor;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JLabel lblQtdVenda;
    private javax.swing.JLabel lblRazaoFab;
    private javax.swing.JLabel lblValorPag;
    private javax.swing.JTextField txtCnpjFab;
    private javax.swing.JTextField txtCpfCli;
    private javax.swing.JTextField txtDataPedido;
    private javax.swing.JTextField txtDescFormaPag;
    private javax.swing.JTextField txtDescProduto;
    private javax.swing.JTextField txtEstAtualProduto;
    private javax.swing.JTextField txtEstMinProduto;
    private javax.swing.JTextField txtIdFormaPag;
    private javax.swing.JTextField txtIdPag;
    private javax.swing.JTextField txtIdPedido;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtIdVendedor;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JTextField txtNomeFab;
    private javax.swing.JTextField txtNomePedido;
    private javax.swing.JTextField txtNomeVendedor;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtQtdVenda;
    private javax.swing.JTextField txtRazaoFab;
    private javax.swing.JTextField txtValorPag;
    // End of variables declaration//GEN-END:variables
}
